### ISSUE TITLE
The description makes it sounds like a browser-controlling package like puppeteer 😅

### ISSUE THREAD

**Issue by fonsp** [adrhill/BrowserMacros.jl#12]
https://pptr.dev/

**Comment by adrhill** [comment]
Good point! Do you have a suggestion?
*"Julia macros to open new browser tabs from the comfort of your REPL."* might be more clear, but also a bit dry!

**Comment by fonsp** [comment]
Julia macros to surf from your REPL to the web?

**Comment by fonsp** [comment]
or just: Surf from your REPL to the web!
